### ISSUE TITLE
java 14 - does not work - Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by johny2000uwb** [rest-assured/rest-assured#1270]
I have tried to test it under OpenJDK 14 ea 34 with error: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

Update the groovy dependency? Maybe: https://issues.apache.org/jira/browse/GROOVY-8843

I have got this call stack:
´´´
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.createMap(ScriptBytecodeAdapter.java:635)
	at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:347)
       ....
´´´

**Comment by markkolich** [comment]
+1 same issue here; Java 14 GA'ed yesterday 3/17 and this issue is completely blocking my stack from moving onto 14.

@johanhaleby perhaps updating to the latest Groovy would help?

**Comment by markkolich** [comment]
FYI for the curious reader - I just upgraded to rest-assured version `4.3.0` and I no longer see these failures with Java 14.

@johny2000uwb perhaps worth another try with the latest version:

https://github.com/rest-assured/rest-assured/releases/tag/rest-assured-4.3.0

**Comment by dragondagda** [comment]
same here. used 4.1.2 before and had the same NoClassDefFoundError. After upgrading to 4.3.0 the failre didn't occur anymore.

**Comment by johanhaleby** [comment]
Yes it's always a good idea to upgrade :)

**Comment by johanhaleby** [comment]
REST Assured has automatic builds on Java 14, see https://github.com/rest-assured/rest-assured/blob/master/.travis.yml.

**Comment by plum117** [comment]
I'm having the same issue and I see that my project use `io.rest-assured:rest-assured:4.3.0` however, maven seem to see that 4.3.0 depends on `org.codehaus.groovy:groovy:2.5.9` instead of groovy 3.0.2.

After investigation, there is a conflict in my project when resolving groovy.version. For me the conflict was with spring-boot-dependencies which was setting groovy.version to 2.5.9.
