### PR TITLE
Migrate from GMaven to GMavenPlus

### PR DESCRIPTION
**Pull request by keeganwitt**
Splitting the migration to GMavenPlus in #1742 into a separate PR.

### CODE REVIEW

**Comment by appiepollo14** [comment]
Works perfectly on JDK11!

**Comment by keeganwitt** [comment]
> Works perfectly on JDK11!

Ah, interesting. I was getting some weird Mockito errors I didn't understand on Java 8.

**Comment by appiepollo14** [comment]
No I'm sorry, It doesn't work like a charm. Mvn clean package does work in fact. But mvn clean install throws the same errors on the integration tests as I've written in my pull request. IMO some groovy exception throwing is different once switching to gmavenplus....?

**Comment by appiepollo14** [comment]
Checkout master, build with JDK 8, works
Checkout master, build with JDK 11 to java 1.8, exception in phase 'class generation' in source unit, unsupported Target MODULE
Checkout master, build with JDK 11, to java 11, with gmavenplus, throws errors as mentioned earlier. 

Any guidance?

**Comment by keeganwitt** [comment]
I don't understand yet why changing plugins would cause a change in behavior. The only thing I can guess is that there's different versions of Groovy dependencies on the classpath during compilation, but I haven't found them yet.

**Comment by appiepollo14** [comment]
Hi @keeganwitt did you figure anything out or have any ideas on how to figure it out? If not I'm kinda stuck

**Comment by keeganwitt** [comment]
> Hi @keeganwitt did you figure anything out or have any ideas on how to figure it out? If not I'm kinda stuck

Not yet. I've reached out to the other Groovy devs to see if they have any ideas. This seems very strange.

**Comment by keeganwitt** [comment]
I can't even build the main branch on Windows, even when using Docker like
```powershell
docker run --rm -v "${HOME}/.m2:/root/.m2" -v "${pwd}:/project" -w /project maven:3.8-eclipse-temurin-11 mvn clean test
```

**Comment by appiepollo14** [comment]
@keeganwitt Im no windhoos user so I can't guide you 🥺

**Comment by keeganwitt** [comment]
What's strange is I'm getting lots of errors like
```
[ERROR] /project/modules/json-schema-validator/src/main/java/io/restassured/module/jsv/JsonSchemaValidator.java:[188,29] cannot find symbol
[ERROR]   symbol:   class JsonSchemaFactory
[ERROR]   location: class io.restassured.module.jsv.JsonSchemaValidator
```
And neither JsonSchemaFactory or JsonSchemaValidator are Groovy classes.

**Comment by keeganwitt** [comment]
Integration tests are failing, but compilation is succeeding.

**Comment by keeganwitt** [comment]
I'm having trouble understanding why it is the tests are failing. I need to understand the tests better I guess.

**Comment by appiepollo14** [comment]
@johanhaleby can you take a look and explain the tests that are failing. Or determine whether they fail as expected or because of the gmaven upgrade and wether we should change the tests accordingly.

**Comment by keeganwitt** [comment]
I'm not sure why. But the tests on this branch pass when I run them in an Ubuntu VM.

**Comment by keeganwitt** [comment]
I created #1757 to ensure the changes run successfully before merging.

**Comment by johanhaleby** [comment]
Unfortunately I have to revert his because lots of tests are failing

**Comment by keeganwitt** [comment]
Failed job: https://github.com/rest-assured/rest-assured/actions/runs/9805509497

**Comment by keeganwitt** [comment]
I finally was able to do a local compilation on Windows (albeit through Docker) to be able to examine what's happening during compilation. I ran this in PowerShell `docker run --rm -v "${HOME}/.m2/repository:/root/.m2/repository" -v "${pwd}:/project" -w /project maven:3-eclipse-temurin-8 mvn clean compile`.

I then inspected the bytecode of the `validate` method of the `ResponseSpecificationImpl$HamcrestAssertionClosure` class. There are major differences. It appears that although Groovy 4 is supposed to always be using invokedynamic, somehow GMaven is removing this optimization. I can't fully explain the behavior differences, but it seems related to this. I noticed the invokedynamic stuff in the failing stacktrace.

```diff
1,22c1,17
<   0 invokestatic #23 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure.$getCallSiteArray : ()[Lorg/codehaus/groovy/runtime/callsite/CallSite;>
<   3 astore_2
<   4 aload_2
<   5 ldc #116 <10>
<   7 aaload
<   8 aload_0
<   9 invokeinterface #65 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;)Ljava/lang/Object;> count 2
<  14 invokestatic #91 <org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.booleanUnbox : (Ljava/lang/Object;)Z>
<  17 ifeq 615 (+598)
<  20 iconst_0
<  21 anewarray #4 <java/lang/Object>
<  24 invokestatic #120 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.createList : ([Ljava/lang/Object;)Ljava/util/List;>
<  27 astore_3
<  28 aload_3
<  29 pop
<  30 aload_2
<  31 ldc #121 <11>
<  33 aaload
<  34 aload_3
<  35 aload_2
<  36 ldc #122 <12>
<  38 aaload
---
>   0 aload_0
>   1 invokedynamic #107 <invoke, BootstrapMethods #7>
>   6 invokedynamic #77 <cast, BootstrapMethods #3>
>  11 ifeq 478 (+467)
>  14 iconst_0
>  15 anewarray #4 <java/lang/Object>
>  18 invokestatic #113 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.createList : ([Ljava/lang/Object;)Ljava/util/List;>
>  21 astore_2
>  22 aload_2
>  23 pop
>  24 aload_2
>  25 aload_0
>  26 aload_1
>  27 invokedynamic #118 <invoke, BootstrapMethods #8>
>  32 invokedynamic #122 <invoke, BootstrapMethods #9>
>  37 pop
>  38 aload_2
25,26c20,21
<  41 invokeinterface #125 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;Ljava/lang/Object;)Ljava/lang/Object;> count 3
<  46 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
---
>  41 invokedynamic #125 <invoke, BootstrapMethods #10>
>  46 invokedynamic #122 <invoke, BootstrapMethods #9>
29,204c24,170
<  53 ldc #128 <13>
<  55 aaload
<  56 aload_3
<  57 aload_2
<  58 ldc #129 <14>
<  60 aaload
<  61 aload_0
<  62 aload_1
<  63 invokeinterface #125 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;Ljava/lang/Object;)Ljava/lang/Object;> count 3
<  68 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
<  73 pop
<  74 aload_2
<  75 ldc #130 <15>
<  77 aaload
<  78 aload_3
<  79 aload_2
<  80 ldc #131 <16>
<  82 aaload
<  83 aload_0
<  84 aload_1
<  85 invokeinterface #125 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;Ljava/lang/Object;)Ljava/lang/Object;> count 3
<  90 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
<  95 pop
<  96 aload_2
<  97 ldc #132 <17>
<  99 aaload
< 100 aload_3
< 101 aload_2
< 102 ldc #133 <18>
< 104 aaload
< 105 aload_0
< 106 aload_1
< 107 invokeinterface #125 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 112 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 117 pop
< 118 aload_2
< 119 ldc #134 <19>
< 121 aaload
< 122 aload_0
< 123 invokeinterface #65 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;)Ljava/lang/Object;> count 2
< 128 invokestatic #91 <org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.booleanUnbox : (Ljava/lang/Object;)Z>
< 131 ifeq 364 (+233)
< 134 aload_2
< 135 ldc #135 <20>
< 137 aaload
< 138 aload_0
< 139 invokeinterface #85 <org/codehaus/groovy/runtime/callsite/CallSite.callGroovyObjectGetProperty : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 144 dup
< 145 ldc #137 <io/restassured/config/RestAssuredConfig>
< 147 invokestatic #42 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.castToType : (Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;>
< 150 checkcast #137 <io/restassured/config/RestAssuredConfig>
< 153 astore 4
< 155 invokestatic #91 <org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.booleanUnbox : (Ljava/lang/Object;)Z>
< 158 ifeq 166 (+8)
< 161 aload 4
< 163 goto 185 (+22)
< 166 aload_2
< 167 ldc #138 <21>
< 169 aaload
< 170 ldc #137 <io/restassured/config/RestAssuredConfig>
< 172 invokeinterface #141 <org/codehaus/groovy/runtime/callsite/CallSite.callConstructor : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 177 ldc #137 <io/restassured/config/RestAssuredConfig>
< 179 invokestatic #42 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.castToType : (Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;>
< 182 checkcast #137 <io/restassured/config/RestAssuredConfig>
< 185 astore 5
< 187 aload 5
< 189 pop
< 190 aload_2
< 191 ldc #142 <22>
< 193 aaload
< 194 aload_0
< 195 invokeinterface #65 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;)Ljava/lang/Object;> count 2
< 200 invokestatic #91 <org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.booleanUnbox : (Ljava/lang/Object;)Z>
< 203 ifeq 259 (+56)
< 206 aload_2
< 207 ldc #143 <23>
< 209 aaload
< 210 aload_0
< 211 invokeinterface #65 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;)Ljava/lang/Object;> count 2
< 216 invokestatic #91 <org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.booleanUnbox : (Ljava/lang/Object;)Z>
< 219 ifne 226 (+7)
< 222 iconst_1
< 223 goto 227 (+4)
< 226 iconst_0
< 227 ifne 247 (+20)
< 230 aload_2
< 231 ldc #144 <24>
< 233 aaload
< 234 aload_0
< 235 invokeinterface #85 <org/codehaus/groovy/runtime/callsite/CallSite.callGroovyObjectGetProperty : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 240 aconst_null
< 241 invokestatic #148 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.compareEqual : (Ljava/lang/Object;Ljava/lang/Object;)Z>
< 244 ifeq 251 (+7)
< 247 iconst_1
< 248 goto 252 (+4)
< 251 iconst_0
< 252 ifeq 259 (+7)
< 255 iconst_1
< 256 goto 260 (+4)
< 259 iconst_0
< 260 ifeq 321 (+61)
< 263 aload_2
< 264 ldc #149 <25>
< 266 aaload
< 267 aload_2
< 268 ldc #150 <26>
< 270 aaload
< 271 ldc #152 <io/restassured/internal/ContentParser>
< 273 invokeinterface #141 <org/codehaus/groovy/runtime/callsite/CallSite.callConstructor : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 278 aload_1
< 279 aload_2
< 280 ldc #153 <27>
< 282 aaload
< 283 aload_0
< 284 invokeinterface #85 <org/codehaus/groovy/runtime/callsite/CallSite.callGroovyObjectGetProperty : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 289 aload 5
< 291 aload_2
< 292 ldc #154 <28>
< 294 aaload
< 295 aload_0
< 296 invokeinterface #65 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;)Ljava/lang/Object;> count 2
< 301 invokeinterface #157 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 6
< 306 astore 6
< 308 aload 6
< 310 ldc #2 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure>
< 312 aload_0
< 313 ldc #159 <contentParser>
< 315 invokestatic #163 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.setGroovyObjectProperty : (Ljava/lang/Object;Ljava/lang/Class;Lgroovy/lang/GroovyObject;Ljava/lang/String;)V>
< 318 aload 6
< 320 pop
< 321 aload_2
< 322 ldc #164 <29>
< 324 aaload
< 325 aload_3
< 326 aload_2
< 327 ldc #165 <30>
< 329 aaload
< 330 aload_2
< 331 ldc #166 <31>
< 333 aaload
< 334 aload_0
< 335 invokeinterface #85 <org/codehaus/groovy/runtime/callsite/CallSite.callGroovyObjectGetProperty : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 340 aload_1
< 341 aload_2
< 342 ldc #167 <32>
< 344 aaload
< 345 aload_0
< 346 invokeinterface #85 <org/codehaus/groovy/runtime/callsite/CallSite.callGroovyObjectGetProperty : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 351 aload 5
< 353 invokeinterface #170 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 5
< 358 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 363 pop
< 364 goto 391 (+27)
< 367 astore 7
< 369 aload_2
< 370 ldc #171 <33>
< 372 aaload
< 373 aload_0
< 374 aload_1
< 375 invokeinterface #125 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 380 pop
< 381 aload 7
< 383 checkcast #173 <java/lang/Throwable>
< 386 athrow
< 387 nop
< 388 goto 391 (+3)
< 391 nop
< 392 goto 400 (+8)
< 395 astore 8
< 397 aload 8
< 399 athrow
< 400 aload_2
< 401 ldc #174 <34>
< 403 aaload
< 404 aload_3
< 405 new #176 <io/restassured/internal/ResponseSpecificationImpl$_HamcrestAssertionClosure_validate_closure2>
---
>  53 aload_0
>  54 aload_1
>  55 invokedynamic #128 <invoke, BootstrapMethods #11>
>  60 invokedynamic #122 <invoke, BootstrapMethods #9>
>  65 pop
>  66 aload_2
>  67 aload_0
>  68 aload_1
>  69 invokedynamic #131 <invoke, BootstrapMethods #12>
>  74 invokedynamic #122 <invoke, BootstrapMethods #9>
>  79 pop
>  80 aload_0
>  81 invokedynamic #134 <invoke, BootstrapMethods #13>
>  86 invokedynamic #77 <cast, BootstrapMethods #3>
>  91 ifeq 271 (+180)
>  94 aload_0
>  95 invokedynamic #137 <getProperty, BootstrapMethods #14>
> 100 dup
> 101 invokedynamic #140 <cast, BootstrapMethods #3>
> 106 astore_3
> 107 invokedynamic #77 <cast, BootstrapMethods #3>
> 112 ifeq 119 (+7)
> 115 aload_3
> 116 goto 131 (+15)
> 119 ldc #142 <io/restassured/config/RestAssuredConfig>
> 121 invokedynamic #146 <init, BootstrapMethods #15>
> 126 invokedynamic #140 <cast, BootstrapMethods #3>
> 131 astore 4
> 133 aload 4
> 135 pop
> 136 aload_0
> 137 invokedynamic #147 <invoke, BootstrapMethods #16>
> 142 invokestatic #97 <org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.booleanUnbox : (Ljava/lang/Object;)Z>
> 145 ifeq 195 (+50)
> 148 aload_0
> 149 invokedynamic #150 <invoke, BootstrapMethods #17>
> 154 invokedynamic #77 <cast, BootstrapMethods #3>
> 159 ifne 166 (+7)
> 162 iconst_1
> 163 goto 167 (+4)
> 166 iconst_0
> 167 ifne 183 (+16)
> 170 aload_0
> 171 invokedynamic #153 <getProperty, BootstrapMethods #18>
> 176 aconst_null
> 177 invokestatic #157 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.compareEqual : (Ljava/lang/Object;Ljava/lang/Object;)Z>
> 180 ifeq 187 (+7)
> 183 iconst_1
> 184 goto 188 (+4)
> 187 iconst_0
> 188 ifeq 195 (+7)
> 191 iconst_1
> 192 goto 196 (+4)
> 195 iconst_0
> 196 ifeq 244 (+48)
> 199 ldc #159 <io/restassured/internal/ContentParser>
> 201 invokedynamic #146 <init, BootstrapMethods #15>
> 206 aload_1
> 207 aload_0
> 208 invokedynamic #162 <getProperty, BootstrapMethods #19>
> 213 aload 4
> 215 aload_0
> 216 invokedynamic #150 <invoke, BootstrapMethods #17>
> 221 invokedynamic #167 <invoke, BootstrapMethods #20>
> 226 astore 5
> 228 aload 5
> 230 ldc #2 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure>
> 232 aload_0
> 233 ldc #152 <contentParser>
> 235 checkcast #169 <java/lang/String>
> 238 invokestatic #173 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.setGroovyObjectProperty : (Ljava/lang/Object;Ljava/lang/Class;Lgroovy/lang/GroovyObject;Ljava/lang/String;)V>
> 241 aload 5
> 243 pop
> 244 aload_2
> 245 aload_0
> 246 invokedynamic #89 <getProperty, BootstrapMethods #5>
> 251 aload_1
> 252 aload_0
> 253 invokedynamic #153 <getProperty, BootstrapMethods #18>
> 258 aload 4
> 260 invokedynamic #177 <invoke, BootstrapMethods #21>
> 265 invokedynamic #122 <invoke, BootstrapMethods #9>
> 270 pop
> 271 goto 291 (+20)
> 274 astore 6
> 276 aload_0
> 277 aload_1
> 278 invokedynamic #180 <invoke, BootstrapMethods #22>
> 283 pop
> 284 aload 6
> 286 checkcast #182 <java/lang/Throwable>
> 289 athrow
> 290 athrow
> 291 goto 299 (+8)
> 294 astore 7
> 296 aload 7
> 298 athrow
> 299 aload_2
> 300 new #184 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure$_validate_closure2>
> 303 dup
> 304 aload_0
> 305 aload_0
> 306 invokespecial #185 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure$_validate_closure2.<init> : (Ljava/lang/Object;Ljava/lang/Object;)V>
> 309 invokedynamic #190 <invoke, BootstrapMethods #23>
> 314 astore 8
> 316 aload 8
> 318 pop
> 319 aload 8
> 321 invokedynamic #193 <invoke, BootstrapMethods #24>
> 326 astore 9
> 328 aload 9
> 330 pop
> 331 aload 9
> 333 iconst_0
> 334 invokestatic #199 <java/lang/Integer.valueOf : (I)Ljava/lang/Integer;>
> 337 invokestatic #202 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.compareGreaterThan : (Ljava/lang/Object;Ljava/lang/Object;)Z>
> 340 ifeq 478 (+138)
> 343 aload_0
> 344 aload_1
> 345 invokedynamic #180 <invoke, BootstrapMethods #22>
> 350 pop
> 351 aload 8
> 353 new #204 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure$_validate_closure3>
> 356 dup
> 357 aload_0
> 358 aload_0
> 359 invokespecial #205 <io/restassured/internal/ResponseSpecificationImpl$HamcrestAssertionClosure$_validate_closure3.<init> : (Ljava/lang/Object;Ljava/lang/Object;)V>
> 362 invokedynamic #208 <invoke, BootstrapMethods #25>
> 367 ldc #210 <
> >
> 369 invokedynamic #215 <invoke, BootstrapMethods #26>
> 374 astore 10
> 376 aload 10
> 378 pop
> 379 aload 9
> 381 iconst_1
> 382 invokestatic #199 <java/lang/Integer.valueOf : (I)Ljava/lang/Integer;>
> 385 invokestatic #202 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.compareGreaterThan : (Ljava/lang/Object;Ljava/lang/Object;)Z>
> 388 ifeq 396 (+8)
> 391 ldc #217 <s>
> 393 goto 398 (+5)
> 396 ldc #219
> 398 astore 11
> 400 aload 11
> 402 pop
> 403 ldc #221 <java/lang/AssertionError>
> 405 new #223 <org/codehaus/groovy/runtime/GStringImpl>
206,221c172,193
< 409 aload_0
< 410 aload_0
< 411 invokespecial #177 <io/restassured/internal/ResponseSpecificationImpl$_HamcrestAssertionClosure_validate_closure2.<init> : (Ljava/lang/Object;Ljava/lang/Object;)V>
< 414 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 419 astore 9
< 421 aload 9
< 423 pop
< 424 aload_2
< 425 ldc #178 <35>
< 427 aaload
< 428 aload 9
< 430 invokeinterface #102 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 435 astore 10
< 437 aload 10
< 439 pop
< 440 aload 10
---
> 409 iconst_4
> 410 anewarray #4 <java/lang/Object>
> 413 dup
> 414 iconst_0
> 415 aload 9
> 417 aastore
> 418 dup
> 419 iconst_1
> 420 aload 11
> 422 aastore
> 423 dup
> 424 iconst_2
> 425 aload 10
> 427 aastore
> 428 dup
> 429 iconst_3
> 430 aload_0
> 431 invokedynamic #226 <getProperty, BootstrapMethods #27>
> 436 aastore
> 437 iconst_5
> 438 anewarray #169 <java/lang/String>
> 441 dup
223,303c195,203
< 443 invokestatic #108 <java/lang/Integer.valueOf : (I)Ljava/lang/Integer;>
< 446 invokestatic #181 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.compareGreaterThan : (Ljava/lang/Object;Ljava/lang/Object;)Z>
< 449 ifeq 610 (+161)
< 452 aload_2
< 453 ldc #182 <36>
< 455 aaload
< 456 aload_0
< 457 aload_1
< 458 invokeinterface #125 <org/codehaus/groovy/runtime/callsite/CallSite.callCurrent : (Lgroovy/lang/GroovyObject;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 463 pop
< 464 aload_2
< 465 ldc #183 <37>
< 467 aaload
< 468 aload_2
< 469 ldc #184 <38>
< 471 aaload
< 472 aload 9
< 474 new #186 <io/restassured/internal/ResponseSpecificationImpl$_HamcrestAssertionClosure_validate_closure3>
< 477 dup
< 478 aload_0
< 479 aload_0
< 480 invokespecial #187 <io/restassured/internal/ResponseSpecificationImpl$_HamcrestAssertionClosure_validate_closure3.<init> : (Ljava/lang/Object;Ljava/lang/Object;)V>
< 483 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 488 ldc #189 <
< >
< 490 invokeinterface #127 <org/codehaus/groovy/runtime/callsite/CallSite.call : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 495 astore 11
< 497 aload 11
< 499 pop
< 500 aload 10
< 502 iconst_1
< 503 invokestatic #108 <java/lang/Integer.valueOf : (I)Ljava/lang/Integer;>
< 506 invokestatic #181 <org/codehaus/groovy/runtime/ScriptBytecodeAdapter.compareGreaterThan : (Ljava/lang/Object;Ljava/lang/Object;)Z>
< 509 ifeq 517 (+8)
< 512 ldc #191 <s>
< 514 goto 519 (+5)
< 517 ldc #193
< 519 astore 12
< 521 aload 12
< 523 pop
< 524 aload_2
< 525 ldc #194 <39>
< 527 aaload
< 528 ldc #196 <java/lang/AssertionError>
< 530 new #198 <org/codehaus/groovy/runtime/GStringImpl>
< 533 dup
< 534 iconst_4
< 535 anewarray #4 <java/lang/Object>
< 538 dup
< 539 iconst_0
< 540 aload 10
< 542 aastore
< 543 dup
< 544 iconst_1
< 545 aload 12
< 547 aastore
< 548 dup
< 549 iconst_2
< 550 aload 11
< 552 aastore
< 553 dup
< 554 iconst_3
< 555 aload_2
< 556 ldc #199 <40>
< 558 aaload
< 559 aload_0
< 560 invokeinterface #85 <org/codehaus/groovy/runtime/callsite/CallSite.callGroovyObjectGetProperty : (Ljava/lang/Object;)Ljava/lang/Object;> count 2
< 565 aastore
< 566 iconst_5
< 567 anewarray #201 <java/lang/String>
< 570 dup
< 571 iconst_0
< 572 ldc #193
< 574 aastore
< 575 dup
< 576 iconst_1
< 577 ldc #203 < expectation>
< 579 aastore
< 580 dup
< 581 iconst_2
< 582 ldc #205 < failed.
---
> 443 ldc #219
> 445 aastore
> 446 dup
> 447 iconst_1
> 448 ldc #228 < expectation>
> 450 aastore
> 451 dup
> 452 iconst_2
> 453 ldc #230 < failed.
305,325c205,219
< 584 aastore
< 585 dup
< 586 iconst_3
< 587 ldc #193
< 589 aastore
< 590 dup
< 591 iconst_4
< 592 ldc #193
< 594 aastore
< 595 invokespecial #208 <org/codehaus/groovy/runtime/GStringImpl.<init> : ([Ljava/lang/Object;[Ljava/lang/String;)V>
< 598 invokeinterface #210 <org/codehaus/groovy/runtime/callsite/CallSite.callConstructor : (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> count 3
< 603 checkcast #173 <java/lang/Throwable>
< 606 athrow
< 607 goto 612 (+5)
< 610 aconst_null
< 611 areturn
< 612 goto 617 (+5)
< 615 aconst_null
< 616 areturn
< 617 aconst_null
< 618 areturn
---
> 455 aastore
> 456 dup
> 457 iconst_3
> 458 ldc #219
> 460 aastore
> 461 dup
> 462 iconst_4
> 463 ldc #219
> 465 aastore
> 466 invokespecial #233 <org/codehaus/groovy/runtime/GStringImpl.<init> : ([Ljava/lang/Object;[Ljava/lang/String;)V>
> 469 invokedynamic #236 <init, BootstrapMethods #15>
> 474 checkcast #182 <java/lang/Throwable>
> 477 athrow
> 478 aconst_null
> 479 areturn
```

**Comment by keeganwitt** [comment]
One idea for moving forward would be downgrade to Groovy 3 (with invokedynamic off, which is the default), then switch to GMavenPlus, then upgrade again, which will bring back invokedynamic.

**Comment by keeganwitt** [comment]
I did a POC for the Groovy 3 path mentioned above. It worked with the exception of two tests I had to ignore: https://github.com/keeganwitt/rest-assured/pull/5.

**Comment by keeganwitt** [comment]
It just occurred to me why this strange behavior happened with GMaven. GMaven never had a version released with the new Maven coordinates of Groovy 4+. This means that it will use the version in the provider, in this case 2.0, which means When you upgraded to Groovy 4, your code actually started getting compiled with Groovy 2.0.1 currently. In order to prevent this you would need to change your plugin exclusion as below
```patch
Subject: Fix GMaven Groovy exclusion
---
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pom.xml b/pom.xml
--- a/pom.xml	(revision e1d96781fe67938078c906cda0a20665033a7c04)
+++ b/pom.xml	(date 1720706672272)
@@ -142,7 +142,7 @@
                             <version>${gmaven.version}</version>
                             <exclusions>
                                 <exclusion>
-                                    <groupId>org.apache.groovy</groupId>
+                                    <groupId>org.codehaus.groovy</groupId>
                                     <artifactId>groovy-all</artifactId>
                                 </exclusion>
                             </exclusions>
```
However, doing so introduces a number of compilation problems itself. This makes me inclined even more to recommend the Groovy 3 route. This was one of the reasons I designed GMavenPlus the way I did. I wanted to make sure the plugin always used the version of Groovy from your project and not some other version from inside itself.

**Comment by keeganwitt** [comment]
New MR with this approach: #1798.
